<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FintechGuard.Pii\FintechGuard.Pii.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>SecureRedact.AspNetCore</PackageId>
    <Version>1.0.0</Version>
    <Authors>Sanket Singh</Authors>
    <Company>Sanket Singh</Company>
    <Description>ASP.NET Core middleware for SecureRedact. Automatically intercepts and masks PII in incoming HTTP request bodies and outgoing JSON responses.</Description>
    <PackageTags>pii;masking;aspnetcore;middleware;redaction;fintech;security</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/sanketsingh001/SecureRedact</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/sanketsingh001/SecureRedact</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
